services:
  web-php82:
    container_name: collectibles
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
    build:
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    volumes:
      - .:/code
